homework3: main.cpp Creature.cpp Gollum.cpp Barbarian.cpp Babayaga.cpp Bluemen.cpp Unicorn.cpp Stack.cpp Stacknode.cpp Queue.cpp Queuenode.cpp
	g++ main.cpp Creature.cpp Gollum.cpp Barbarian.cpp Babayaga.cpp Bluemen.cpp Unicorn.cpp Stack.cpp Stacknode.cpp Queue.cpp Queuenode.cpp -o homework4
